/**
 * File generated by 'tools/collision-generator.py' and 'assets/raw/collision-map.col' to simplify handling collisions.
 *
 * DO NOT EDIT MANUALLY
 */

#include <core/types.h>
#include <collision.h>
#include <error.h>

#include <GFraMe/gfmObject.h>
#include <GFraMe/gfmQuadtree.h>
#include <GFraMe/gfmSprite.h>

#if defined(DEBUG) && !(defined(__WIN32) || defined(__WIN32__))
#include <stdlib.h>
#include <signal.h>
#endif /* defined(DEBUG) && !(defined(__WIN32) || defined(__WIN32__)) */


/**
 * Retrieve the type and all the children for a given object.
 *
 * @param  [ in]node The object (with a valid gfmObject)
 */
static void _collision_getSubtype(struct collision_node *node) {
	gfmObject_getChild(&node->child, &node->type, node->object);

	if (node->type == gfmType_sprite && node->child) {
		node->sprite = (gfmSprite*)node->child;
		gfmSprite_getChild(&node->child, &node->type, node->sprite);
	}
}


int collision_handle(gfmQuadtreeRoot *qt) {
	struct collision_node node1 = {0};
	struct collision_node node2 = {0};
	gfmRV grv = GFMRV_OK;
	int rv = 0;

	ASSERT_OK(
		rv = gfmQuadtree_getOverlaping(&node1.object, &node2.object, qt),
		__ret
	);

	/* Filter out self-collision. */
	if (node1.object == node2.object) {
		goto __ret;
	}

	_collision_getSubtype(&node1);
	_collision_getSubtype(&node2);

	switch(MERGE_TYPES(node1.type, node2.type)) {
		/* ===== collision_handleFloor ===== */
		case MERGE_TYPES(TYP_FLOOR, TYP_PLAYER):
			ASSERT_OK(rv = collision_handleFloor(&node1, &node2), __ret);
			break;
		case MERGE_TYPES(TYP_PLAYER, TYP_FLOOR):
			ASSERT_OK(rv = collision_handleFloor(&node2, &node1), __ret);
			break;

		/* ===== collision_explodeRainbow ===== */
		case MERGE_TYPES(TYP_FLOOR, BTYP_PARTICLE):
		case MERGE_TYPES(TYP_SPIKES, BTYP_PARTICLE):
			ASSERT_OK(rv = collision_explodeRainbow(&node1, &node2), __ret);
			break;
		case MERGE_TYPES(BTYP_PARTICLE, TYP_FLOOR):
		case MERGE_TYPES(BTYP_PARTICLE, TYP_SPIKES):
			ASSERT_OK(rv = collision_explodeRainbow(&node2, &node1), __ret);
			break;

		/* ===== collision_handleSpikes ===== */
		case MERGE_TYPES(TYP_SPIKES, TYP_PLAYER):
			ASSERT_OK(rv = collision_handleSpikes(&node1, &node2), __ret);
			break;
		case MERGE_TYPES(TYP_PLAYER, TYP_SPIKES):
			ASSERT_OK(rv = collision_handleSpikes(&node2, &node1), __ret);
			break;

		/* ===== collision_handlePlayerLoader ===== */
		case MERGE_TYPES(TYP_PLAYER, TYP_LOADER):
			ASSERT_OK(rv = collision_handlePlayerLoader(&node1, &node2), __ret);
			break;
		case MERGE_TYPES(TYP_LOADER, TYP_PLAYER):
			ASSERT_OK(rv = collision_handlePlayerLoader(&node2, &node1), __ret);
			break;

		/* ===== collision_yokuBlock ===== */
		case MERGE_TYPES(TYP_PLAYER, TYP_YOKU_BLOCK):
		case MERGE_TYPES(BTYP_PARTICLE, TYP_YOKU_BLOCK):
			ASSERT_OK(rv = collision_yokuBlock(&node1, &node2), __ret);
			break;
		case MERGE_TYPES(TYP_YOKU_BLOCK, TYP_PLAYER):
		case MERGE_TYPES(TYP_YOKU_BLOCK, BTYP_PARTICLE):
			ASSERT_OK(rv = collision_yokuBlock(&node2, &node1), __ret);
			break;

		/* ===== collision_getGem ===== */
		case MERGE_TYPES(TYP_PLAYER, TYP_GEM):
			ASSERT_OK(rv = collision_getGem(&node1, &node2), __ret);
			break;
		case MERGE_TYPES(TYP_GEM, TYP_PLAYER):
			ASSERT_OK(rv = collision_getGem(&node2, &node1), __ret);
			break;

		/* ===== Ignore collisions ===== */
		case MERGE_TYPES(TYP_FLOOR, TYP_FLOOR):
		case MERGE_TYPES(TYP_FLOOR, TYP_SPIKES):
		case MERGE_TYPES(TYP_FLOOR, TYP_TITLE):
		case MERGE_TYPES(TYP_FLOOR, TYP_OPTION):
		case MERGE_TYPES(TYP_FLOOR, TYP_LOADER):
		case MERGE_TYPES(TYP_FLOOR, TYP_YOKU_BLOCK):
		case MERGE_TYPES(TYP_FLOOR, TYP_YOKU_CONTROLLER):
		case MERGE_TYPES(TYP_FLOOR, TYP_GEM):
		case MERGE_TYPES(TYP_SPIKES, TYP_FLOOR):
		case MERGE_TYPES(TYP_SPIKES, TYP_SPIKES):
		case MERGE_TYPES(TYP_SPIKES, TYP_TITLE):
		case MERGE_TYPES(TYP_SPIKES, TYP_OPTION):
		case MERGE_TYPES(TYP_SPIKES, TYP_LOADER):
		case MERGE_TYPES(TYP_SPIKES, TYP_YOKU_BLOCK):
		case MERGE_TYPES(TYP_SPIKES, TYP_YOKU_CONTROLLER):
		case MERGE_TYPES(TYP_SPIKES, TYP_GEM):
		case MERGE_TYPES(TYP_PLAYER, TYP_PLAYER):
		case MERGE_TYPES(TYP_PLAYER, TYP_TITLE):
		case MERGE_TYPES(TYP_PLAYER, TYP_OPTION):
		case MERGE_TYPES(TYP_PLAYER, BTYP_PARTICLE):
		case MERGE_TYPES(TYP_PLAYER, TYP_YOKU_CONTROLLER):
		case MERGE_TYPES(TYP_TITLE, TYP_FLOOR):
		case MERGE_TYPES(TYP_TITLE, TYP_SPIKES):
		case MERGE_TYPES(TYP_TITLE, TYP_PLAYER):
		case MERGE_TYPES(TYP_TITLE, TYP_TITLE):
		case MERGE_TYPES(TYP_TITLE, TYP_OPTION):
		case MERGE_TYPES(TYP_TITLE, TYP_LOADER):
		case MERGE_TYPES(TYP_TITLE, BTYP_PARTICLE):
		case MERGE_TYPES(TYP_TITLE, TYP_YOKU_BLOCK):
		case MERGE_TYPES(TYP_TITLE, TYP_YOKU_CONTROLLER):
		case MERGE_TYPES(TYP_TITLE, TYP_GEM):
		case MERGE_TYPES(TYP_OPTION, TYP_FLOOR):
		case MERGE_TYPES(TYP_OPTION, TYP_SPIKES):
		case MERGE_TYPES(TYP_OPTION, TYP_PLAYER):
		case MERGE_TYPES(TYP_OPTION, TYP_TITLE):
		case MERGE_TYPES(TYP_OPTION, TYP_OPTION):
		case MERGE_TYPES(TYP_OPTION, TYP_LOADER):
		case MERGE_TYPES(TYP_OPTION, BTYP_PARTICLE):
		case MERGE_TYPES(TYP_OPTION, TYP_YOKU_BLOCK):
		case MERGE_TYPES(TYP_OPTION, TYP_YOKU_CONTROLLER):
		case MERGE_TYPES(TYP_OPTION, TYP_GEM):
		case MERGE_TYPES(TYP_LOADER, TYP_FLOOR):
		case MERGE_TYPES(TYP_LOADER, TYP_SPIKES):
		case MERGE_TYPES(TYP_LOADER, TYP_TITLE):
		case MERGE_TYPES(TYP_LOADER, TYP_OPTION):
		case MERGE_TYPES(TYP_LOADER, TYP_LOADER):
		case MERGE_TYPES(TYP_LOADER, BTYP_PARTICLE):
		case MERGE_TYPES(TYP_LOADER, TYP_YOKU_BLOCK):
		case MERGE_TYPES(TYP_LOADER, TYP_YOKU_CONTROLLER):
		case MERGE_TYPES(TYP_LOADER, TYP_GEM):
		case MERGE_TYPES(BTYP_PARTICLE, TYP_PLAYER):
		case MERGE_TYPES(BTYP_PARTICLE, TYP_TITLE):
		case MERGE_TYPES(BTYP_PARTICLE, TYP_OPTION):
		case MERGE_TYPES(BTYP_PARTICLE, TYP_LOADER):
		case MERGE_TYPES(BTYP_PARTICLE, BTYP_PARTICLE):
		case MERGE_TYPES(BTYP_PARTICLE, TYP_YOKU_CONTROLLER):
		case MERGE_TYPES(BTYP_PARTICLE, TYP_GEM):
		case MERGE_TYPES(TYP_YOKU_BLOCK, TYP_FLOOR):
		case MERGE_TYPES(TYP_YOKU_BLOCK, TYP_SPIKES):
		case MERGE_TYPES(TYP_YOKU_BLOCK, TYP_TITLE):
		case MERGE_TYPES(TYP_YOKU_BLOCK, TYP_OPTION):
		case MERGE_TYPES(TYP_YOKU_BLOCK, TYP_LOADER):
		case MERGE_TYPES(TYP_YOKU_BLOCK, TYP_YOKU_BLOCK):
		case MERGE_TYPES(TYP_YOKU_BLOCK, TYP_YOKU_CONTROLLER):
		case MERGE_TYPES(TYP_YOKU_BLOCK, TYP_GEM):
		case MERGE_TYPES(TYP_YOKU_CONTROLLER, TYP_FLOOR):
		case MERGE_TYPES(TYP_YOKU_CONTROLLER, TYP_SPIKES):
		case MERGE_TYPES(TYP_YOKU_CONTROLLER, TYP_PLAYER):
		case MERGE_TYPES(TYP_YOKU_CONTROLLER, TYP_TITLE):
		case MERGE_TYPES(TYP_YOKU_CONTROLLER, TYP_OPTION):
		case MERGE_TYPES(TYP_YOKU_CONTROLLER, TYP_LOADER):
		case MERGE_TYPES(TYP_YOKU_CONTROLLER, BTYP_PARTICLE):
		case MERGE_TYPES(TYP_YOKU_CONTROLLER, TYP_YOKU_BLOCK):
		case MERGE_TYPES(TYP_YOKU_CONTROLLER, TYP_YOKU_CONTROLLER):
		case MERGE_TYPES(TYP_YOKU_CONTROLLER, TYP_GEM):
		case MERGE_TYPES(TYP_GEM, TYP_FLOOR):
		case MERGE_TYPES(TYP_GEM, TYP_SPIKES):
		case MERGE_TYPES(TYP_GEM, TYP_TITLE):
		case MERGE_TYPES(TYP_GEM, TYP_OPTION):
		case MERGE_TYPES(TYP_GEM, TYP_LOADER):
		case MERGE_TYPES(TYP_GEM, BTYP_PARTICLE):
		case MERGE_TYPES(TYP_GEM, TYP_YOKU_BLOCK):
		case MERGE_TYPES(TYP_GEM, TYP_YOKU_CONTROLLER):
		case MERGE_TYPES(TYP_GEM, TYP_GEM):
			{/* Do nothing */}
			break;
		default: {
			/* Unfiltered collision, do something about it */
#if defined(DEBUG) && !(defined(__WIN32) || defined(__WIN32__))
			raise(SIGINT);
#endif /* defined(DEBUG) && !(defined(__WIN32) || defined(__WIN32__)) */
		} break;
	}

__ret:
	return grv || rv;
}
