import argparse
import importlib
import pathlib

file_manip = importlib.import_module('file-manip')

def main() -> None:
	"""preloaded-map-generator's entrypoint.

	Parses all arguments, then generates the output file
	based on the level directoy.
	"""

	parser = argparse.ArgumentParser(
		prog='preloaded-map-generator',
		description='Generates a hard-coded array of maps to be preloaded for kitten-v2',
	)
	parser.add_argument(
		'src_dir',
		help='The input directory with every map',
		type=str,
	)
	parser.add_argument(
		'dest_dir',
		help='The output directory where the generated C files is stored',
		type=str,
	)
	parser.add_argument(
		'--rm',
		help='Remove the previous destination directory, if it exists',
		action='store_true',
		default=False,
	)

	args = parser.parse_args()

	# Check that the dest_dir is within the project's directory,
	# and then create it.
	project_dir = (pathlib.Path(__file__) / '../..')
	dest_dir = file_manip.create_dir(args.dest_dir, project_dir, args.rm)

	src_dir = (pathlib.Path(args.src_dir)).resolve()

	# Generate the preloaded list.
	generate_preloaded(src_dir, dest_dir)

def generate_preloaded(src_dir: pathlib.Path, dest_dir: pathlib.Path) -> None:
	"""Generates the list of preloaded maps to as a C file.

	:param pathlib.Path src_dir: Directory where the input files that will be preloaded are located.
	:param pathlib.Path dest_dir: Directory where the output file(s) shall be written.
	"""

	# Collect every map within the directory.
	maps = list_maps(src_dir)

	# Generate the C code.
	gen_code(dest_dir / 'auto_preloaded_map.c', maps)


def list_maps(src_dir: pathlib.Path) -> list[str]:
	"""Collects every directory name (the maps) within the supplied directory.

	:param pathlib.Path src_dir: Directory to be inspected.
	:return list[str]: The list of maps found in supplied directory.
	"""

	ret: list[str] = []

	for child in src_dir.iterdir():
		if not child.is_dir():
			continue

		# Find the first path within assets.
		idx = -1
		while child.parts[idx] != 'assets':
			idx -= 1
		idx += 1

		# Recreate the map name from the found parts.
		map_name = None
		while idx < 0:
			if map_name is None:
				map_name = pathlib.Path(child.parts[idx])
			else:
				map_name = map_name / child.parts[idx]
			idx += 1

		ret.append(str(map_name))

	return ret


def gen_code(out_file: pathlib.Path, maps: list[str]) -> None:
	"""Generates the output code.

	:param pathlib.Path out_file: The output file to be generated.
	:param list[str] maps: The list of maps to be preloaded.
	"""

	with out_file.open('wb') as file:
		file.write("""/**
 * File generated by 'tools/preloaded-map-generator.py' to list every map to be preloaded.
 *
 * DO NOT EDIT MANUALLY
 */

#include <error.h>


struct mapName {
	/** The name of the map. */
	const char * const name;
	/** The length of the name, assuming no terminating '\0'. */
	int len;
};


/** List of every available preloaded map. */
static struct mapName mapNames[] = {""".encode('utf-8'))

		for name in maps:
			file.write(f"""
	{{
		"{name}",
		{len(name)},
	}},""".encode('utf-8'))

		file.write("""
};


#define COUNT (sizeof(mapNames) / sizeof(struct mapName))


int preloadedMap_getName(char **name, int *len, int idx) {
	int rv = 1;

	ASSERT(idx < COUNT, __ret);

	*name = (char*)mapNames[idx].name;
	*len = mapNames[idx].len;

	rv = 0;
__ret:
	return 0;
}


int preloadedMap_getCount(int *count) {
	*count = COUNT;
	return 0;
}
""".encode('utf-8'))


if __name__ == '__main__':
	main()
